-- House of Mercy: Supabase/PostgreSQL schema replacing the SQLite store.
-- Auth model: custom username/password (scrypt) + opaque server-side sessions, implemented by the
-- `hom-api` Edge Function (service role). Browser roles (anon/authenticated) get NO table access.

-- ===== Identity / workspace (maps SQLite users, workspaces, memberships, sessions) =====
create table public.workspaces (
  id text primary key,
  name text not null,
  created_at timestamptz not null default now()
);

create table public.app_users (
  id uuid primary key default gen_random_uuid(),
  username text not null check (username ~ '^[A-Za-z0-9_-]{3,30}$'),
  first_name text not null,
  last_name text not null,
  name text not null,
  pw_salt text not null,                 -- scrypt salt (hex); same scheme as the Node server
  pw_hash text not null,                 -- scrypt(64) hash (hex); never plaintext
  password_requires_change boolean not null default false,
  account_status text not null default 'Active' check (account_status in ('Active','Suspended','Pending Password Setup')),
  created_at timestamptz not null default now(),
  last_login timestamptz
);
create unique index app_users_username_ci on public.app_users (lower(username));

create table public.memberships (
  workspace_id text not null references public.workspaces(id) on delete cascade,
  user_id uuid not null references public.app_users(id) on delete cascade,
  role text not null check (role in ('Admin','Editor','Contributor')),
  created_at timestamptz not null default now(),
  primary key (workspace_id, user_id)
);
create index memberships_user on public.memberships(user_id);

create table public.sessions (
  token_hash text primary key,           -- sha256 of the opaque token; token itself is never stored
  user_id uuid not null references public.app_users(id) on delete cascade,
  created_at timestamptz not null default now(),
  expires_at timestamptz not null
);
create index sessions_user on public.sessions(user_id);

create table public.login_attempts (
  id bigint generated always as identity primary key,
  key text not null,
  at timestamptz not null default now()
);
create index login_attempts_key on public.login_attempts(key, at);

-- ===== Existing app data (maps SQLite items, kv, comments, activity) =====
create sequence public.items_seq start 1000000; -- migrated rows keep their small legacy seq values; new rows sort above them
create table public.items (
  workspace_id text not null references public.workspaces(id) on delete cascade,
  collection text not null check (collection in ('ideas','reminders','goals','analytics','hashtagSets','imports')),
  id text not null,
  data jsonb not null,
  seq bigint not null default nextval('public.items_seq'),
  primary key (workspace_id, collection, id)
);
create index items_ws on public.items(workspace_id, collection, seq desc);

create table public.kv (
  workspace_id text not null references public.workspaces(id) on delete cascade,
  key text not null,
  data jsonb not null,
  primary key (workspace_id, key)
);

create table public.comments (
  id text primary key,
  workspace_id text not null references public.workspaces(id) on delete cascade,
  target_kind text not null,
  target_id text not null,
  parent_id text,
  user_id uuid not null,
  user_name text not null,
  body text not null,
  created_at timestamptz not null default now()
);
create index comments_target on public.comments(workspace_id, target_kind, target_id);

create table public.activity (
  id bigint generated by default as identity primary key,
  workspace_id text not null references public.workspaces(id) on delete cascade,
  user_id uuid,
  user_name text not null,
  text text not null,
  created_at timestamptz not null default now()
);
create index activity_ws on public.activity(workspace_id, id desc);

-- ===== Content system (Idea -> Calendar -> Assignment -> Published -> Meta -> AI -> Idea) =====
-- Every row carries workspace_id; composite FKs keep related rows inside one workspace.
create table public.content_ideas (
  id uuid primary key default gen_random_uuid(),
  workspace_id text not null references public.workspaces(id) on delete cascade,
  title text not null, notes text, category text, platform text,
  status text not null default 'Ideas' check (status in ('Ideas','Developing','Review','Approved','Planned')),
  created_by uuid references public.app_users(id) on delete set null,
  assignee_id uuid references public.app_users(id) on delete set null,
  legacy_item_id text,
  created_at timestamptz not null default now(), updated_at timestamptz not null default now(),
  unique (workspace_id, id)
);
create table public.campaigns (
  id uuid primary key default gen_random_uuid(),
  workspace_id text not null references public.workspaces(id) on delete cascade,
  name text not null, description text, starts_on date, ends_on date,
  created_at timestamptz not null default now(),
  unique (workspace_id, id)
);
create table public.calendar_items (
  id uuid primary key default gen_random_uuid(),
  workspace_id text not null references public.workspaces(id) on delete cascade,
  idea_id uuid, campaign_id uuid,
  title text not null, platform text, scheduled_for timestamptz,
  status text not null default 'Planned',
  assignee_id uuid references public.app_users(id) on delete set null,
  created_by uuid references public.app_users(id) on delete set null,
  created_at timestamptz not null default now(), updated_at timestamptz not null default now(),
  unique (workspace_id, id),
  foreign key (workspace_id, idea_id) references public.content_ideas(workspace_id, id) on delete set null (idea_id),
  foreign key (workspace_id, campaign_id) references public.campaigns(workspace_id, id) on delete set null (campaign_id)
);
create table public.goals (
  id uuid primary key default gen_random_uuid(),
  workspace_id text not null references public.workspaces(id) on delete cascade,
  title text not null, target text, due_on date, status text,
  created_at timestamptz not null default now(), unique (workspace_id, id)
);
create table public.reminders (
  id uuid primary key default gen_random_uuid(),
  workspace_id text not null references public.workspaces(id) on delete cascade,
  title text not null, remind_at timestamptz, done boolean not null default false,
  created_at timestamptz not null default now(), unique (workspace_id, id)
);
create table public.events (
  id uuid primary key default gen_random_uuid(),
  workspace_id text not null references public.workspaces(id) on delete cascade,
  title text not null, starts_at timestamptz, ends_at timestamptz, location text, notes text,
  created_at timestamptz not null default now(), unique (workspace_id, id)
);
create table public.meta_imports (
  id uuid primary key default gen_random_uuid(),
  workspace_id text not null references public.workspaces(id) on delete cascade,
  platform text not null, report_type text not null,
  imported_at timestamptz not null default now(),
  range_start date, range_end date,
  record_count integer not null default 0,
  available_metrics text[] not null default '{}',
  file_hash text not null,                         -- sha256 of file contents; blocks accidental re-import
  raw_data jsonb,                                  -- raw imported rows preserved
  imported_by uuid references public.app_users(id) on delete set null,
  unique (workspace_id, id),
  unique (workspace_id, file_hash)
);
create table public.published_content (
  id uuid primary key default gen_random_uuid(),
  workspace_id text not null references public.workspaces(id) on delete cascade,
  calendar_item_id uuid, idea_id uuid,
  platform text, external_id text, url text, caption text, published_at timestamptz,
  created_at timestamptz not null default now(),
  unique (workspace_id, id),
  foreign key (workspace_id, calendar_item_id) references public.calendar_items(workspace_id, id) on delete set null (calendar_item_id),
  foreign key (workspace_id, idea_id) references public.content_ideas(workspace_id, id) on delete set null (idea_id)
);
create table public.content_analytics (
  id uuid primary key default gen_random_uuid(),
  workspace_id text not null references public.workspaces(id) on delete cascade,
  published_content_id uuid, meta_import_id uuid,
  -- Metrics are nullable: unavailable metrics stay NULL, never zero/fabricated.
  reach bigint, impressions bigint, views bigint, likes bigint, comments bigint, shares bigint,
  saves bigint, clicks bigint, follows bigint, watch_time_seconds numeric,
  metric_date date, raw_row jsonb,
  created_at timestamptz not null default now(),
  unique (workspace_id, id),
  foreign key (workspace_id, published_content_id) references public.published_content(workspace_id, id) on delete cascade,
  foreign key (workspace_id, meta_import_id) references public.meta_imports(workspace_id, id) on delete set null (meta_import_id)
);
create table public.hashtags (
  id uuid primary key default gen_random_uuid(),
  workspace_id text not null references public.workspaces(id) on delete cascade,
  set_name text, platform text, tag text not null,
  created_at timestamptz not null default now(), unique (workspace_id, id)
);
create table public.ai_recommendations (
  id uuid primary key default gen_random_uuid(),
  workspace_id text not null references public.workspaces(id) on delete cascade,
  idea_id uuid, kind text not null, body jsonb not null,
  source_refs jsonb not null default '[]',        -- which authorized records informed it
  created_by uuid references public.app_users(id) on delete set null,
  created_at timestamptz not null default now(),
  unique (workspace_id, id),
  foreign key (workspace_id, idea_id) references public.content_ideas(workspace_id, id) on delete set null (idea_id)
);

-- ===== Row Level Security =====
-- RLS is enabled on every table. Browser roles have no grants and an explicit deny policy, so a
-- publishable key can never read or write data directly. Only the hom-api Edge Function (service
-- role, bypasses RLS) touches these tables, and it derives workspace_id from the validated session,
-- never from client input.
do $$
declare t text;
begin
  for t in select tablename from pg_tables where schemaname='public' loop
    execute format('alter table public.%I enable row level security', t);
    execute format('revoke all on public.%I from anon, authenticated', t);
    execute format('create policy %I on public.%I as restrictive for all to anon, authenticated using (false) with check (false)', 'deny_browser_'||t, t);
  end loop;
end $$;
revoke all on sequence public.items_seq from anon, authenticated;

-- ===== Last-admin guards (atomic; service role only) =====
create function public.hom_active_admins(ws text) returns integer language sql stable as $$
  select count(*)::int from public.memberships m join public.app_users u on u.id=m.user_id
  where m.workspace_id=ws and m.role='Admin' and u.account_status<>'Suspended'
$$;

create function public.hom_set_role(ws text, uid uuid, new_role text) returns void language plpgsql as $$
declare cur text;
begin
  perform 1 from public.memberships where workspace_id=ws and role='Admin' for update;
  select role into cur from public.memberships where workspace_id=ws and user_id=uid;
  if cur is null then raise exception 'NOT_FOUND'; end if;
  if cur='Admin' and new_role<>'Admin' and public.hom_active_admins(ws)<=1 then raise exception 'LAST_ADMIN'; end if;
  update public.memberships set role=new_role where workspace_id=ws and user_id=uid;
end $$;

create function public.hom_set_status(ws text, uid uuid, new_status text) returns text language plpgsql as $$
declare cur_role text; cur_status text; pending boolean; result text;
begin
  perform 1 from public.memberships where workspace_id=ws and role='Admin' for update;
  select m.role, u.account_status, u.password_requires_change into cur_role, cur_status, pending
    from public.memberships m join public.app_users u on u.id=m.user_id where m.workspace_id=ws and u.id=uid;
  if cur_role is null then raise exception 'NOT_FOUND'; end if;
  if new_status='Suspended' and cur_status<>'Suspended' and cur_role='Admin' and public.hom_active_admins(ws)<=1 then raise exception 'LAST_ADMIN'; end if;
  result := case when new_status='Suspended' then 'Suspended' when pending then 'Pending Password Setup' else 'Active' end;
  update public.app_users set account_status=result where id=uid;
  if result='Suspended' then delete from public.sessions where user_id=uid; end if;
  return result;
end $$;

create function public.hom_remove_member(ws text, uid uuid) returns void language plpgsql as $$
declare cur text;
begin
  perform 1 from public.memberships where workspace_id=ws and role='Admin' for update;
  select role into cur from public.memberships where workspace_id=ws and user_id=uid;
  if cur is null then raise exception 'NOT_FOUND'; end if;
  if cur='Admin' and public.hom_active_admins(ws)<=1 then raise exception 'LAST_ADMIN'; end if;
  delete from public.memberships where workspace_id=ws and user_id=uid;
  update public.items set data = data || '{"assigneeId":"","assignee":""}'::jsonb
    where workspace_id=ws and data->>'assigneeId'=uid::text;
end $$;

revoke execute on all functions in schema public from public, anon, authenticated;
grant execute on all functions in schema public to service_role;

insert into public.workspaces(id, name) values ('house-of-mercy', 'House of Mercy') on conflict do nothing;
